package main

import (
	"encoding/json"
	"flag"
	"fmt"
	"log"
	"os"

	"github.com/WolcenOn/Supermarket-Prices-API/internal/canonicalanalysis"
	"github.com/WolcenOn/Supermarket-Prices-API/internal/canonicalruleproposal"
)

func main() {
	inputPath := flag.String("input", "", "canonical analysis JSON generated by canonical-analyze (required; use - for stdin)")
	outputPath := flag.String("output", "-", "output JSON path, or - for stdout")
	minSupport := flag.Int("min-support", 3, "minimum number of products supporting a semantic pattern")
	minConcentration := flag.Float64("min-concentration", 0.70, "minimum dominant-category concentration for a proposal")
	maxPerFamily := flag.Int("max-per-family", 20, "maximum proposals emitted for each anchor family")
	flag.Parse()

	if *inputPath == "" {
		log.Fatal("--input is required")
	}

	input, err := openInput(*inputPath)
	if err != nil {
		log.Fatal(err)
	}
	if input != os.Stdin {
		defer input.Close()
	}

	var analysis canonicalanalysis.Report
	decoder := json.NewDecoder(input)
	if err := decoder.Decode(&analysis); err != nil {
		log.Fatalf("decode canonical analysis: %v", err)
	}

	report := canonicalruleproposal.Propose(analysis, canonicalruleproposal.Options{
		MinSupport: *minSupport,
		MinConcentration: *minConcentration,
		MaxPerFamily: *maxPerFamily,
	})

	output, err := openOutput(*outputPath)
	if err != nil {
		log.Fatal(err)
	}
	if output != os.Stdout {
		defer output.Close()
	}

	encoder := json.NewEncoder(output)
	encoder.SetIndent("", "  ")
	if err := encoder.Encode(report); err != nil {
		log.Fatalf("encode proposals: %v", err)
	}
}

func openInput(path string) (*os.File, error) {
	if path == "-" {
		return os.Stdin, nil
	}
	file, err := os.Open(path)
	if err != nil {
		return nil, fmt.Errorf("open input %s: %w", path, err)
	}
	return file, nil
}

func openOutput(path string) (*os.File, error) {
	if path == "" || path == "-" {
		return os.Stdout, nil
	}
	file, err := os.Create(path)
	if err != nil {
		return nil, fmt.Errorf("create output %s: %w", path, err)
	}
	return file, nil
}
